console.log('salut');
console.log('le js c cool');
console.log('le js c cool et marrant');
console.log('le js c cool et marrant et facile');
console.log('le js c cool et marrant');
console.log('le js c cool et marrant et facile');
console.log('le js c cool');
console.log('le js c cool et marrant');
console.log('le js c cool et marrant et facile');
console.log('le js c cool et marrant');
console.log('le js c cool et marrant et facile');