name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

on:
  pull_request:
    branches: ["main"]

jobs:
  snykScan:
    uses: ./.github/workflows/snyk-security.yml
    secrets: 
      SNYK_TOKEN : ${{ secrets.SNYK_TOKEN }}
  Deploy-Preview:
    needs: snykScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Run Snyk Code test
        id: snyk
        run: snyk code test --all-projects --json || echo "::set-output name=exitcode::1"
      - name: Check Snyk Code test results
        run: |
          if [[ "${{ steps.snyk.outcome }}" == "success" ]]; then
            echo "url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_ENV
          else
            echo "Snyk detected security issues, deployment to Vercel is blocked."
            exit 1
          fi
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          if [[ "${{ steps.snyk.outcome }}" == "success" ]]; then
            echo "url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" >> $GITHUB_OUTPUT
          else
            echo "Snyk detected security issues, deployment to Vercel is blocked."
            exit 1
          fi
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'The preview URL is: ${{ steps.deploy.outputs.url }}.'
            });